### ISSUE TITLE
Please upload v0.1.2

### ISSUE THREAD

**Issue by k4zy** [m1noon/Disco#3]
Please upload diff of this commit :pray: https://github.com/m1noon/Disco/commit/1ddb0108f8799903db3712d2a1a79d06a0633444#diff-5c959112ef0c27180e34c21a220eee03

**Comment by m1noon** [comment]
I'm Sorry release is delayed.
I had released new version '0.1.2'.

**Comment by k4zy** [comment]
Thanks a lot!! :)
